# Generated by Django 3.2.9 on 2021-11-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student')], max_length=10, null=True),
        ),
    ]
